---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart steve-web
  ansible.builtin.systemd:
    name: steve-web
    state: restarted
  become: true
